title: Harish Pallepati # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  Pricing Analyst at Volvo 
  <br>
  Masters in Business Analytics at UT,Dallas
  <br><br>
  I have over 4 years of experience in delivering analytical solutions as Marketing and Finance domains.
  As I'm about to graduate in May'2019, I look forward for an opportunity to carry on my passion towards analytics.
  Feel free to reach me at <a href = "pallepatiharishrao@gmail.com">Email</a>
  <br><br>
  <a href="https://www.linkedin.com/in/harishraopallepati/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
